# Generated by Django 4.1.1 on 2022-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEmotionChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('review_time', models.CharField(max_length=10)),
                ('positive_chat_count', models.IntegerField()),
                ('neturality_chat_count', models.IntegerField()),
                ('negative_chat_count', models.IntegerField()),
                ('question_chat_count', models.IntegerField()),
                ('total_chat_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('chat_time', models.CharField(max_length=20)),
                ('chat_name', models.CharField(max_length=30)),
                ('chat_comment', models.CharField(max_length=100)),
            ],
        ),
    ]
